spring.application.name=SpringBootCountryServiceProject

# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=studentDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=doochi567
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver